name: Reusable Deploy
# on: workflow_call # this allow calling from workflow
on:
    workflow_call:
        inputs:
            artifact-name:
                description: The name of deployable artifact files
                required: false
                default: public
                type: string
  
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/download-artifact@v4
              with:
                name: ${{ inputs.artifact-name}}  # Downloading file/artifact from another work flow
            - name: List Files
              run: ls

